### ISSUE TITLE
Support Object Types

### ISSUE THREAD

**Issue by rafalp** [mirumee/ariadne-graphql-modules#22]
Next API should support GraphQL `type` definition.

# TODO

- [x] Define fields using `field: type` syntax
- [x] Define fields using `field = ObjectType.field(...)` syntax
- [x] Define fields using `field: type = ObjectType.field(...)` syntax
- [x] Define fields using `@ObjectType.field(...)` syntax
- [x] Define type using `__schema__ = gql(...)` syntax
- [x] Define fields resolvers using `@ObjectType.resolver()`
- [x] Define fields returning default scalars
- [x] Define fields returning custom types
- [x] Define fields arguments on resolvers for built-in GraphQL scalars
- [x] Customize fields arguments behavior
- [x] Define fields arguments on resolvers for custom scalars
- [x] Define fields arguments on resolvers for input types
- [x] Define fields aliases using `__aliases__` magic attribute
- [x] Set outnames on fields arguments
- [x] Validate field names in `@ObjectType.resolver()`
- [x] Validate args names in `@ObjectType.resolver()`
- [x] Validate args names in `@ObjectType.field()`
- [x] Validate args out names in `@ObjectType.resolver()`
- [x] Validate args out names in `@ObjectType.field()`
- [x] Validate double descriptions on types
- [x] Validate double descriptions on fields
- [x] Validate double descriptions on arguments

**Comment by rafalp** [comment]
Done in #32
