### ISSUE TITLE
Support scalar types

### ISSUE THREAD

**Issue by rafalp** [mirumee/ariadne-graphql-modules#25]
# TODO

- [x] Define scalar type using code first approach
- [x] Define scalar type using schema first approach
- [x] Set serializer
- [x] Set value parser
- [x] Set literal parser
- [x] Set description using `__description__` attribute
- [x] Set description using `__schema__` attribute
